version: "3"
services:
  back:
    build: .
    ports:
      - "8888:5000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1

  rabbitmq:
    build: .
    hostname: rabbit
    image: rabbitmq:3-management
    command: rabbitmq-server
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=shotping
      - RABBITMQ_DEFAULT_PASS=shotping
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - back